### PR TITLE
ignore removed files

### PR DESCRIPTION
**Pull request by zzgab**
When deleting a large file from the repository, the check should not fail because of the removed file...

### CODE REVIEW

**Comment by ppremk** [comment]
@zzgab thank you for this PR. Forgive me for not circling back soon on this.

**Comment by zzgab** [comment]
Hi @ppremk, any updates on this? How can I help you with the review?
Thanks

**Review by ppremk — APPROVED** [review]
LGTM Let's 🚢 @zzgab

**Comment by ppremk** [comment]
Apologies, It is now merged @zzgab 🙇🏽 . Thank you for the contribution once again ❤️ 🎉

**Comment by ppremk** [comment]
I will cut a new release soon. Pending the merge from another open PR

**Pull request merged**
